"""Synthesis Strategy Plugin.

Evaluates the routes provided by the retrosynthesis plugin and scores them
based on complexity, step count, and estimated viability.
"""
import logging
from typing import Any, Dict

from app.services.plugins.base import BasePlugin

logger = logging.getLogger(__name__)


class StrategyPlugin(BasePlugin):

    @property
    def name(self) -> str:
        return "evaluate_strategy"

    @property
    def description(self) -> str:
        return (
            "Evaluate a list of synthesis routes and return a feasibility score "
            "for each route based on step count, starting materials, and known bottlenecks. "
            "Helps choose the best synthesis path."
        )

    async def load(self) -> Any:
        return True

    async def execute(self, model: Any, **kwargs) -> dict:
        """Run synthesis strategy evaluation.

        Args (in kwargs):
            routes: list -- List of route dictionaries from plan_synthesis.

        Returns:
            Dict containing the evaluated routes.
        """
        routes = kwargs.get("routes", [])
        if not routes or not isinstance(routes, list):
            return {"valid": False, "error": "Missing or invalid 'routes' argument. Must be a list."}

        evaluated_routes = []
        for route in routes:
            # We will use simple heuristics for now
            # In a real scenario, this could use another model or complex logic
            
            steps = route.get("number_of_steps", 0)
            materials_count = len(route.get("starting_materials", []))
            base_score = route.get("score", 0.5)
            
            # Simple heuristic scoring: shorter routes with fewer materials are better
            # Normalize to 0-1 scale approx
            step_penalty = steps * 0.1
            material_penalty = max(0, materials_count - 2) * 0.05
            
            feasibility = max(0.1, min(0.99, base_score - step_penalty - material_penalty + 0.3))
            
            # Determine difficulty
            if steps > 5 or feasibility < 0.4:
                difficulty = "Hard"
            elif steps > 3 or feasibility < 0.7:
                difficulty = "Medium"
            else:
                difficulty = "Easy"
                
            evaluated_routes.append({
                "route_index": route.get("route_index", 0),
                "original_score": base_score,
                "feasibility_score": round(feasibility, 2),
                "difficulty": difficulty,
                "estimated_yield": "Unknown (needs reaction review)",
                "bottlenecks": f"Route has {steps} steps. Review literature for typical yields." if steps > 4 else "None obvious"
            })
            
        # Sort by feasibility descending
        evaluated_routes.sort(key=lambda x: x["feasibility_score"], reverse=True)

        return {
            "valid": True,
            "routes_evaluated": len(evaluated_routes),
            "recommendation": f"Route {evaluated_routes[0]['route_index']} appears most feasible.",
            "scored_routes": evaluated_routes
        }

    def input_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "routes": {
                    "type": "array",
                    "description": "List of routes generated by plan_synthesis tool",
                    "items": {
                        "type": "object"
                    }
                }
            },
            "required": ["routes"],
        }

    def output_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "valid": {"type": "boolean"},
                "error": {"type": "string"},
                "routes_evaluated": {"type": "integer"},
                "recommendation": {"type": "string"},
                "scored_routes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "route_index": {"type": "integer"},
                            "original_score": {"type": "number"},
                            "feasibility_score": {"type": "number"},
                            "difficulty": {"type": "string"},
                            "estimated_yield": {"type": "string"},
                            "bottlenecks": {"type": "string"}
                        }
                    }
                }
            },
        }
