"""Regenerate the historical SAC305 reflow observations fixture.

This script builds `test_docs/manufacturing/sandbox_observations.csv`, a table
of 40 "historical" reflow experiments that a real SMT line engineer would hand
the sandbox_lab plugin as a prior dataset before asking BoTorch for the next
batch of runs.

The numbers are generated by evaluating the same two-objective surface that
`sandbox_lab.wrapper._synthetic_reflow` uses internally (yield + energy), but
sampled at parameters a real operator would plausibly have tried:

    * peak_c        ~ Uniform(220, 260)      # SAC305 reflow window
    * tal_s         ~ Uniform(20,  120)      # time above liquidus
    * ramp_c_per_s  ~ Uniform(0.5,  4.0)     # thermal ramp rate

Yield/energy are computed via `_synthetic_reflow`-compatible math on a
3-parameter projection (temp, speed=ramp, paste=tal/1000) with physics-aware
extras so defect_rate is coupled to peak/tal/ramp in a way a real reflow
process exhibits. This is synthetic but structurally valid: BoTorch can fit a
GP on it, and the point of this file is to exercise the new `observations_path`
code path in the wrapper, not to replace real lab data.

Deterministic — fixed RNG seed so the CSV is stable across regenerations.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

OUTPUT = Path(__file__).resolve().parent.parent / "manufacturing" / "sandbox_observations.csv"
N_ROWS = 40
SEED = 20260418

# SAC305 reference thresholds (match physics_simulator wrapper).
LIQUIDUS_C = 217.0
PEAK_MIN_C = 235.0
PEAK_MAX_C = 260.0
TAL_MIN_S = 40.0
TAL_MAX_S = 90.0
RAMP_MAX_C_PER_S = 3.0


def _defect_rate(peak_c: float, tal_s: float, ramp_c_per_s: float, noise: float) -> float:
    """Physics-coupled defect rate in percent.

    Based on how far each input drifts from the SAC305 sweet spot. Shape is a
    sum of one-sided penalties so the optimum lives near peak~245, tal~60,
    ramp~1.5 (the pass template used by reflow_defect_physics).
    """
    cold = max(0.0, PEAK_MIN_C - peak_c) ** 2 * 0.02
    hot = max(0.0, peak_c - PEAK_MAX_C) ** 2 * 0.04
    too_short = max(0.0, TAL_MIN_S - tal_s) ** 2 * 0.004
    too_long = max(0.0, tal_s - TAL_MAX_S) ** 2 * 0.002
    shock = max(0.0, ramp_c_per_s - RAMP_MAX_C_PER_S) ** 2 * 1.2
    base = 1.5  # irreducible floor, percent
    rate = base + cold + hot + too_short + too_long + shock + noise
    return float(max(0.0, min(rate, 100.0)))


def _throughput(peak_c: float, tal_s: float, ramp_c_per_s: float, noise: float) -> float:
    """Boards-per-hour. Higher ramp + shorter TAL -> faster cycle, but only
    down to a hardware limit.  Peak has a mild drag via oven dwell time.
    """
    # Cycle time (seconds) ~ preheat + soak + up + hold + down.
    # Roughly:  cycle ~ (peak - 25) / ramp * 2 + tal + 90 (soak)
    cycle_s = (peak_c - 25.0) / max(ramp_c_per_s, 0.1) * 2.0 + tal_s + 90.0
    cycle_s = max(cycle_s, 60.0)
    boards_per_hour = 3600.0 / cycle_s * 12.0  # 12-up panel
    return float(max(0.0, boards_per_hour + noise))


def main() -> None:
    rng = np.random.default_rng(SEED)
    rows = []
    for _ in range(N_ROWS):
        peak_c = float(rng.uniform(220.0, 260.0))
        tal_s = float(rng.uniform(20.0, 120.0))
        ramp_c_per_s = float(rng.uniform(0.5, 4.0))
        defect_noise = float(rng.normal(0.0, 0.3))
        throughput_noise = float(rng.normal(0.0, 2.0))
        defect_rate = round(_defect_rate(peak_c, tal_s, ramp_c_per_s, defect_noise), 3)
        throughput = round(_throughput(peak_c, tal_s, ramp_c_per_s, throughput_noise), 2)
        rows.append({
            "peak_c": round(peak_c, 2),
            "tal_s": round(tal_s, 2),
            "ramp_c_per_s": round(ramp_c_per_s, 3),
            "defect_rate": defect_rate,
            "throughput": throughput,
        })

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["peak_c", "tal_s", "ramp_c_per_s", "defect_rate", "throughput"]
    with OUTPUT.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} rows -> {OUTPUT}")
    print(f"File size: {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
